### ISSUE TITLE
[feat]: add gitlab-ci.yaml coverage

### ISSUE THREAD

**Issue by ioggstream** [par-tec/python-cookiecutter#53]
## I expect

- [ ] gitlab-ci.yaml to highlight code coverage

## Instead

- no code coverage
- 

## Notes

see https://docs.gitlab.com/ee/ci/testing/test_coverage_visualization/

```yaml
job:
 ...
# From: https://docs.gitlab.com/ee/ci/testing/code_coverage.html#test-coverage-examples
  coverage: /TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/

  # From: https://docs.gitlab.com/ee/ci/testing/test_coverage_visualization/cobertura.html#python-example
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
```
